### PR TITLE
Adds gold standard F matrix as the default (Closes #161)

### LINKED ISSUE #161: As a user, I can apply the Gold Standard F Estimation Method

### PR DESCRIPTION
**Pull request by jlaura**

### CODE REVIEW

**Comment by jlaura** [comment]
Example at: https://gist.github.com/jlaura/341e94532b4b455bd16077b8e12c9c79

**Comment by jlaura** [comment]
@all this is the OS X build hanging on download / install and not on us.  I still need to have a look at the coverage issues.

**Comment by jlaura** [comment]
@all this is good to go - possible to have this in before demos during the Monday retro?

**Comment by Kelvinrr** [comment]
Just looked it over, I don't see any major problems.

**Pull request merged**
