### PR TITLE
Second draft of python software tutorial

### PR DESCRIPTION
**Pull request by bwh33l3r**
This is a tutorial notebook that goes over numpy, pandas, and matplotlib. The purpose is for the upcoming workshop on Autocnet as an introduction.

### CODE REVIEW

**Review by jessemapel — APPROVED** [review]
Looks good

**Comment by jlaura** [comment]
@jessemapel @bwh33l3r Is this something that we can and/or should look getting merged this week? I am happy to cover this under the current work.

**Comment by jessemapel** [comment]
Yes this should get merged in. I'm not sure why it has merge conflicts though.

**Comment by jessemapel** [comment]
@bwh33l3r Go ahead and squash and merge this once it's ready

**Comment by bwh33l3r** [comment]
I think this is ready to merge if someone with write access wants to do it.

**Pull request merged**
