### PR TITLE
Added Dockerfile for autocnet environment

### PR DESCRIPTION
**Pull request by evindunn**
Containerized Linux dev environment for autocnet

### CODE REVIEW

**Comment by evindunn** [comment]
@jlaura with the environment.yml included in this pr, my container runs the tests no problem. Maybe we should try it with Travis?

**Comment by Kelvinrr** [comment]
The problem is that `.travis.yml` is installing the latest version of NetworkX which updated to 2.0 like a month ago. We need to set the NetworkX requirement to 1.11 until we can go in and update everything to correspond with the 2.0 release.

**Comment by evindunn** [comment]
Reworking the deps for docker image to match up with new networkx

**Comment by jlaura** [comment]
:+1: The linux builds are all passing.  Travis OS X is slow as dirt recently...

**Pull request merged**
