### PR TITLE
naive_template test/fix

### PR DESCRIPTION
**Pull request by evindunn**

### CODE REVIEW

**Comment by Kelvinrr** [comment]
The test is currently failing because travis is trying to build the environment using python 3.5 which we don't currently support as far as I know (3.6 causes dependency conflicts) I'll test locally. You can ignore travis tests for now. We have been having trouble with travis for a while now.

**Comment by Kelvinrr** [comment]
Before a merge, probably be a good idea to squash these commits (https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) if you have any issues, feel free to ask me or Adam.

**Comment by jlaura** [comment]
@evindunn Also, let's merge the changes that @Kelvinrr made to travis so that we have a clean CI environment.  One of us can assist Tuesday AM or Wed.

**Comment by evindunn** [comment]
Thanks for your help guys, I look forward getting this right. If there's anything I can do from home, let me know.

**Comment by jlaura** [comment]
:+1: great job guys!

**Pull request merged**
