### PR TITLE
Passed ratio_checks keyword args to edge.ratio_check

### PR DESCRIPTION
**Pull request by acpaquette**
Keyword arguments weren't being passed through correctly.

### CODE REVIEW

**Comment by acpaquette** [comment]
Why were all of those methods removed, I use them in the image_match black box.

**Comment by Kelvinrr** [comment]
Did you pull from remote before making your changes? Looks like you are adding some stuff that was removed.

**Comment by Kelvinrr** [comment]
Did you pull before you made your changes? Edge operations in network.py were removed because apply_func_to_edges did the same functionality. Look at "tutorials with visualization" for examples on how to use it.

**Comment by acpaquette** [comment]
Okay sounds good, I will remove the edge operations from this PR then.

**Comment by Kelvinrr** [comment]
👍

**Pull request merged**
