### PR TITLE
Remote

### PR DESCRIPTION
**Pull request by jlaura**
This PR demonstrates how to get the bin scripts working properly with a remote jupyterhub kernel. We set enough other env variables that it is not longer concerning to set one more.

### CODE REVIEW

**Comment by jessemapel** [comment]
This doesn't look like it actually does anything with the `bin` directory set in the config

**Comment by jlaura** [comment]
@jessemapel I need to blackout the first file. The second adds the bin and then render the ipynb to see how the path gets patched in.

**Comment by jlaura** [comment]
Fixed the erroneous include. This file is updated in another PR.

**Comment by jessemapel** [comment]
Manually updating the PATH in the notebook is not a good solution in my opinion. using something like [shutil.which](https://docs.python.org/dev/library/shutil.html#shutil.which) to check if the script is already in the path and if it's not checking the bin config variable inside the library makes more sense.

Right now, there is no reason to even have the bin in the config, it can just be a variable in the notebook.

**Pull request closed without merging**
