### PR TITLE
Pep8 for Matcher and graph

### PR DESCRIPTION
**Pull request by acpaquette**

### CODE REVIEW

**Comment by jlaura** [comment]
This has merge conflicts.  Pull from upstream, merge, and then push.

**Comment by acpaquette** [comment]
Pulled from upstream master, merged with upstream master, and pushed says everything is up to date but there are still merge conflicts.

**Comment by acpaquette** [comment]
I'll probably just drop this PR, reset the branch and try again.

**Comment by jlaura** [comment]
@acpaquette Is this PR dead?  If not, go ahead and reopen.

**Pull request closed without merging**
