### PR TITLE
Adds the UCL ring matcher to autocnet

### PR DESCRIPTION
**Pull request by jlaura**

### CODE REVIEW

**Comment by Kelvinrr** [comment]
Is this good to go? Is travis broken on Autocnet or is it this PR? Can't tell by looking at logs.

**Comment by jlaura** [comment]
@acpaquette This PR includes the updates for autocnet_server - I had not realized that this was still open, but the UCL ring matcher also needs to be PRed in for everything to be working.

**Comment by jlaura** [comment]
@all this is passing all tests locally ` 194 passed, 26 warnings in 48.27 seconds` Changes in here are for the autocnet_server API such as having matches on edges as properties and not straight up attributes.

**Comment by jlaura** [comment]
Looks like cv2 updated in the container....ugghhh - I'll work more on this PR to get it passing.

**Comment by jlaura** [comment]
:+1: I will get to this today.  I should have some downtime at this conference.

**Comment by jlaura** [comment]
@acpaquette or @Kelvinrr Can you pull this local and run the test.  I can not get the edge failure reproduced locally.

**Pull request merged**
