### PR TITLE
documentation and other tweaks

### PR DESCRIPTION
**Pull request by kree**

### CODE REVIEW

**Comment by jlaura** [comment]
I see that build #84 passed - did you rerun this same PR with a new build?  The code looks clean and I see a seg fault on Travis' side.  Saw this earlier today and it looks like an issue with --with-coverage that is external to us.

**Comment by kree** [comment]
Build #84 seems to be for PR #20. I did try re-starting the travis build for this PR, but it consistently segfaults. I just tried again and the results are the same.

**Comment by kree** [comment]
Yes, that was it!

**Comment by jlaura** [comment]
Awesome!  Looks like it would make sense to check what the change from 3.0.0 to 3.1.0 is - a future item.

**Pull request merged**
