### PR TITLE
Bug fixes in Demo notebook and for Demo notebook

### PR DESCRIPTION
**Pull request by ladoramkershner**
Errors that probably have been seen previously and fixed locally. Mostly just adding ['data'] for source and destination images and fixing typos

Took out height parameter from ng.place_points_in_overlaps()

### CODE REVIEW

**Comment by Kelvinrr** [comment]
If no ones has objections I'll merge this once/if the CI passes.

**Comment by jlaura** [comment]
@Kelvinrr I am not sure how CI is/will pass with all of the additional `['data']` lines. Is this to fix something that I broke in my last PR or something else?

**Comment by Kelvinrr** [comment]
No idea where or when it happened, been using ISIS so I never ran into it. the test will definitely fail because the test assumes that the data key doesn't have to be there so the problem seems to be the code was written as some point assuming a node data object but place_points_in_overlaps is passing the dictionary instead.

**Comment by jlaura** [comment]
Scratch my comment because I was just referencing a not merged alteration (the other open PR). This PR should probably merge first to keep everyone rolling. Then I can deal with the merge issues and get the other PR updated. Does that sound reasonable?

**Comment by Kelvinrr** [comment]
you talking about #345? Yeah it sounds reasonable, I am trying to merge this one ASAP. without it no one can really move forward.

**Comment by jlaura** [comment]
@Kelvinrr yup

**Pull request merged**
